<?php

function shift_cipher_menu() {
  $items['shift_cipher'] = array(
      'title' => 'Shift Cipher',
      'page callback' => 'drupal_core_files',
      'access callback' => TRUE,
      'page arguments' => array('shift_cipher_form'),
      'type' => MENU_NORMAL_ITEM,
  );

  $items['shift_cipher_results_page'] = array(
      'title' => 'Results',
      'page callback' => 'shift_cipher_results',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK;
  );

  return $items;
}
