<?php

function shift_cipher_menu() {
  $items['shift_cipher'] = array(
      'title' => 'Shift Cipher',
      'page callback' => 'drupal_get_form',
      'access callback' => TRUE,
      'page arguments' => array('shift_cipher_form'),
      'type' => MENU_NORMAL_ITEM,
  );

  $items['shift_cipher_results_page'] = array(
      'title' => 'Results',
      'page callback' => 'shift_cipher_results',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );

  return $items;
}

function shift_cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift Value',
    '#type' => 'textfield',
    '#description' => t('Enter the shift value'),
    '#element_validate' => array('element_validate_number'),
    '#required' => TRUE,
  );

  $form['direction'] = array(
    '#title' => 'Direction',
    '#type' => 'textfield',
    '#description' => t('Enter the shift direction'),
    // '#element_validate' => array('element_validate_left_right'),
    '#required' => TRUE,
  );

  $form['phrase'] = array(
    '#title' => 'Phrase',
    '#type' => 'textfield',
    '#description' => t('Enter the phrase to be shift ciphered'),
    // '#element_validate' => array('element_validate_text'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Shift Cipher Your Phrase!',
  );

  return $form;
}

function shift_cipher_form_submit($form, &$form_state) {
  $shift_value = $form_state['values']['shift_value'];
  $direction = $form_state['values']['direction'];
  $phrase = $form_state['values']['phrase'];

  $letters = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');

  $split_string = str_split($phrase);
  $cipher_array = array();

  foreach ($split_string as $single_letter) {
    $find_key = array_search($single_letter, $letters);
    $find_key = $find_key + $shift_value;
    $new_letter = $letters[$find_key];
    array_push($cipher_array, $new_letter);
    }
    $_SESSION['result'] = implode($cipher_array);
    $form_state['redirect'] = 'shift_cipher_results_page';
}


function shift_cipher_results() {
  return $_SESSION['result'];
}
